name: Laravel

on:
  push:
    branches: [ master ]

jobs:  
  build-assets:
    runs-on: ubuntu-latest
    steps:
    - name: npm install and build
    - run: |
        npm install
        npm run prod
    
